INSERT INTO recipes (id,title,description,mood_tag,cuisine,category,difficulty,prep_time_minutes,cook_time_minutes,servings,estimated_cost,is_trending) VALUES
(1,'Chicken Karahi','Smoky wok-cooked chicken in a spicy tomato masala','indulgent','Pakistani','Main Course','Medium',15,35,4,450,TRUE),
(2,'Daal Chawal','Silky yellow lentils served over steamed basmati rice','comfort','Pakistani','Main Course','Easy',10,30,3,120,TRUE),
(3,'Chicken Biryani','Fragrant layered rice with marinated chicken and whole spices','indulgent','Pakistani','Main Course','Hard',30,60,5,600,TRUE),
(4,'Nihari','Slow-cooked beef shank stew with aromatic spices','comfort','Pakistani','Main Course','Hard',20,180,4,550,FALSE),
(5,'Aloo Keema','Spiced minced beef with potatoes in a thick gravy','comfort','Pakistani','Main Course','Easy',10,25,3,300,FALSE),
(6,'Chana Masala','Hearty chickpea curry with tangy tomatoes and spices','healthy','Pakistani','Main Course','Easy',10,25,3,180,FALSE),
(7,'Palak Gosht','Tender lamb cooked in a fresh spinach gravy','healthy','Pakistani','Main Course','Medium',15,45,4,480,FALSE),
(8,'Haleem','Slow-cooked wheat and meat porridge deeply spiced','comfort','Pakistani','Main Course','Hard',20,120,5,400,TRUE),
(9,'Aloo Paratha','Crispy flatbread stuffed with spiced mashed potato','comfort','Pakistani','Breakfast','Easy',15,20,2,100,FALSE),
(10,'Chapli Kebab','Flat minced beef patties fried with pomegranate seeds','indulgent','Pakistani','Snack','Medium',15,15,3,280,TRUE),
(11,'Butter Chicken','Tender chicken in a rich creamy tomato sauce','indulgent','Indian','Main Course','Medium',15,30,4,420,TRUE),
(12,'Palak Paneer','Fresh cottage cheese cubes in a smooth spinach gravy','healthy','Indian','Main Course','Easy',10,20,3,280,FALSE),
(13,'Chole Bhature','Spiced chickpeas served with deep-fried puffy bread','indulgent','Indian','Main Course','Medium',20,30,3,220,FALSE),
(14,'Masala Dosa','Crispy rice crepe with a spiced potato filling','healthy','Indian','Breakfast','Medium',30,15,2,180,TRUE),
(15,'Rajma Chawal','Kidney bean curry served with basmati rice','comfort','Indian','Main Course','Easy',10,35,3,160,FALSE),
(16,'Paneer Tikka','Marinated cottage cheese grilled until charred','indulgent','Indian','Snack','Easy',15,15,3,300,FALSE),
(17,'Dal Makhani','Black lentils slow-cooked with butter and cream','indulgent','Indian','Main Course','Hard',10,120,4,350,TRUE),
(18,'Aloo Gobi','Dry-spiced cauliflower and potato stir fry','healthy','Indian','Main Course','Easy',10,20,3,150,FALSE),
(19,'Samosa','Crispy pastry triangles filled with spiced potato and peas','comfort','Indian','Snack','Medium',20,20,4,120,TRUE),
(20,'Biryani Pulao','Aromatic rice cooked with whole spices and caramelised onions','comfort','Indian','Main Course','Medium',10,30,3,250,FALSE),
(21,'Spaghetti Carbonara','Silky pasta with eggs, pecorino and guanciale','indulgent','Italian','Main Course','Medium',5,20,2,380,TRUE),
(22,'Margherita Pizza','Thin-crust pizza with tomato, mozzarella and fresh basil','comfort','Italian','Main Course','Medium',20,15,2,350,TRUE),
(23,'Chicken Pasta','Penne with grilled chicken in a rich cream sauce','indulgent','Italian','Main Course','Easy',10,20,2,400,FALSE),
(24,'Mushroom Risotto','Slow-stirred Arborio rice with porcini and parmesan','indulgent','Italian','Main Course','Hard',5,35,2,450,FALSE),
(25,'Bruschetta','Grilled bread topped with fresh tomatoes, basil and garlic','healthy','Italian','Snack','Easy',5,5,4,150,FALSE),
(26,'Lasagna','Layered pasta baked with meat sauce and bechamel','indulgent','Italian','Main Course','Hard',30,60,6,700,TRUE),
(27,'Pesto Pasta','Pasta tossed in a vibrant basil and pine nut pesto','healthy','Italian','Main Course','Easy',5,12,2,300,FALSE),
(28,'Minestrone Soup','Chunky vegetable soup with pasta and beans','healthy','Italian','Soup','Easy',15,30,4,200,FALSE),
(29,'Arancini','Crispy deep-fried risotto balls with melted cheese','indulgent','Italian','Snack','Hard',20,15,4,300,FALSE),
(30,'Tiramisu','Espresso-soaked ladyfingers layered with mascarpone','indulgent','Italian','Dessert','Medium',20,0,6,500,FALSE),
(31,'Egg Fried Rice','Wok-tossed rice with eggs, vegetables and soy sauce','comfort','Chinese','Main Course','Easy',5,10,2,150,TRUE),
(32,'Kung Pao Chicken','Stir-fried chicken with peanuts and Sichuan chillies','indulgent','Chinese','Main Course','Medium',15,15,3,380,TRUE),
(33,'Pork Dumplings','Steamed pork and cabbage dumplings in bamboo baskets','indulgent','Chinese','Snack','Hard',40,15,4,500,FALSE),
(34,'Sweet and Sour Chicken','Crispy chicken in a tangy pineapple sauce','comfort','Chinese','Main Course','Medium',15,20,3,400,FALSE),
(35,'Hot and Sour Soup','Tangy spicy broth with tofu, mushrooms and egg','healthy','Chinese','Soup','Easy',5,15,3,180,FALSE),
(36,'Chow Mein','Stir-fried noodles with vegetables and chicken','comfort','Chinese','Main Course','Easy',10,15,2,250,FALSE),
(37,'Mapo Tofu','Silken tofu in a fiery Sichuan bean sauce','healthy','Chinese','Main Course','Easy',5,15,2,200,FALSE),
(38,'Spring Rolls','Crispy rolls filled with vegetables and glass noodles','comfort','Chinese','Snack','Medium',20,15,4,180,FALSE),
(39,'Char Siu Pork','Cantonese BBQ pork glazed with honey and five spice','indulgent','Chinese','Main Course','Medium',15,40,3,450,TRUE),
(40,'Wonton Soup','Pork-filled wontons in a clear ginger broth','comfort','Chinese','Soup','Medium',30,15,3,280,FALSE),
(41,'Bibimbap','Rice bowl with vegetables, egg and gochujang','healthy','Korean','Main Course','Medium',20,20,2,350,TRUE),
(42,'Tteokbokki','Chewy rice cakes in a spicy sweet gochujang sauce','comfort','Korean','Snack','Easy',5,15,2,200,TRUE),
(43,'Korean Fried Chicken','Double-fried chicken glazed with sweet spicy sauce','indulgent','Korean','Main Course','Hard',15,30,3,500,TRUE),
(44,'Japchae','Stir-fried glass noodles with vegetables and sesame','healthy','Korean','Main Course','Medium',15,15,3,320,FALSE),
(45,'Sundubu Jjigae','Soft tofu stew with seafood and kimchi','comfort','Korean','Soup','Easy',5,20,2,280,FALSE),
(46,'Kimchi Fried Rice','Fried rice stir-fried with aged kimchi and sesame oil','comfort','Korean','Main Course','Easy',5,10,2,180,FALSE),
(47,'Galbi','Grilled marinated beef short ribs','indulgent','Korean','Main Course','Medium',240,15,3,700,FALSE),
(48,'Pajeon','Crispy savoury pancakes with spring onions and seafood','comfort','Korean','Snack','Easy',10,10,2,250,FALSE),
(49,'Doenjang Jjigae','Fermented soybean paste stew with tofu','healthy','Korean','Soup','Easy',5,15,2,200,FALSE),
(50,'Korean Ramyeon','Spicy noodles with egg, spam and vegetables','comfort','Korean','Main Course','Easy',2,8,1,150,FALSE),
(51,'Desi Tacos','Spiced chicken tikka in soft tortillas with raita','indulgent','Fusion','Main Course','Easy',15,15,3,380,TRUE),
(52,'Korean BBQ Burger','Bulgogi beef patty with kimchi slaw and gochujang mayo','indulgent','Fusion','Main Course','Medium',20,15,2,550,TRUE),
(53,'Masala Mac and Cheese','Pasta baked in a spiced cheddar tomato sauce','comfort','Fusion','Main Course','Easy',10,25,3,350,FALSE),
(54,'Sushi Burrito','Giant sushi roll with rice, avocado and salmon','healthy','Fusion','Main Course','Medium',25,0,2,600,TRUE),
(55,'Tandoori Quesadilla','Tortilla filled with tandoori chicken and melted cheese','indulgent','Fusion','Snack','Easy',10,10,2,350,FALSE),
(56,'Ramen Carbonara','Carbonara technique applied to Japanese ramen noodles','indulgent','Fusion','Main Course','Medium',5,15,2,400,FALSE),
(57,'Mango Avocado Salad','Sweet mango, creamy avocado with chilli lime dressing','healthy','Fusion','Salad','Easy',10,0,2,300,FALSE),
(58,'Kimchi Grilled Cheese','Sourdough grilled cheese stuffed with spicy kimchi','comfort','Fusion','Snack','Easy',5,8,1,250,TRUE),
(59,'Peri Peri Biryani','Biryani layered with peri peri marinated chicken','indulgent','Fusion','Main Course','Hard',30,60,4,650,FALSE),
(60,'Thai Tikka Noodles','Chicken tikka tossed in a coconut peanut noodle sauce','indulgent','Fusion','Main Course','Medium',15,20,2,420,TRUE),
(61,'Avocado Toast','Sourdough topped with smashed avocado and chilli flakes','healthy','Western','Breakfast','Easy',5,5,1,250,FALSE),
(62,'Cheese Omelette','Fluffy omelette filled with melted cheddar and herbs','healthy','Western','Breakfast','Easy',3,7,1,120,FALSE),
(63,'Garlic Bread','Crispy baguette slathered in herb garlic butter','comfort','Italian','Snack','Easy',5,8,4,150,FALSE),
(64,'Nachos','Tortilla chips loaded with cheese, jalapenos and salsa','indulgent','Mexican','Snack','Easy',5,8,3,280,TRUE),
(65,'Soft Boiled Eggs','Perfectly runny soft-boiled eggs with toast soldiers','healthy','Western','Breakfast','Easy',2,7,1,80,FALSE),
(66,'Banana Smoothie','Blended banana with yogurt, honey and oats','healthy','Western','Breakfast','Easy',5,0,1,120,FALSE),
(67,'Quesadilla','Crispy tortilla filled with cheese and mixed peppers','comfort','Mexican','Snack','Easy',5,8,2,200,FALSE),
(68,'Peanut Butter Toast','Toast spread with peanut butter and banana slices','comfort','Western','Breakfast','Easy',3,3,1,100,FALSE),
(69,'Paratha with Chai','Crispy layered flatbread with cardamom tea','comfort','Pakistani','Breakfast','Easy',10,10,2,80,FALSE),
(70,'Aloo Samosa','Crispy pastry filled with spiced potato and peas','comfort','Pakistani','Snack','Medium',20,20,6,150,TRUE),
(71,'Beef Steak','Pan-seared ribeye with garlic butter and rosemary','indulgent','Western','Main Course','Medium',5,12,2,800,FALSE),
(72,'Grilled Salmon','Oven-roasted salmon fillet with lemon and dill','healthy','Western','Main Course','Easy',5,15,2,650,FALSE),
(73,'Chicken Caesar Salad','Romaine, croutons and grilled chicken with Caesar dressing','healthy','Western','Salad','Easy',15,10,2,380,FALSE),
(74,'Lamb Chops','Herb-marinated lamb chops grilled to perfection','indulgent','Western','Main Course','Medium',60,12,2,750,FALSE),
(75,'BBQ Chicken','Smoky grilled chicken basted in homemade BBQ sauce','comfort','Western','Main Course','Easy',15,30,3,450,TRUE),
(76,'Fish and Chips','Beer-battered fish with thick-cut fried potatoes','indulgent','British','Main Course','Medium',15,20,2,500,FALSE),
(77,'Beef Tacos','Seasoned ground beef in crispy taco shells','comfort','Mexican','Main Course','Easy',10,15,3,380,FALSE),
(78,'Chicken Shawarma','Marinated chicken wrapped in flatbread with garlic sauce','comfort','Middle Eastern','Main Course','Medium',30,20,3,350,TRUE),
(79,'Mutton Korma','Lamb in a rich almond and yogurt gravy','indulgent','Pakistani','Main Course','Hard',20,60,4,650,FALSE),
(80,'Thai Green Curry','Coconut milk curry with chicken and Thai basil','indulgent','Thai','Main Course','Easy',10,20,3,420,TRUE),
(81,'Tomato Basil Soup','Blended roasted tomatoes with fresh basil and cream','comfort','Italian','Soup','Easy',10,25,3,200,FALSE),
(82,'Lentil Soup','Hearty red lentil soup with cumin and lemon','healthy','Middle Eastern','Soup','Easy',5,25,4,150,FALSE),
(83,'Greek Salad','Cucumber, tomatoes, olives and feta with oregano dressing','healthy','Greek','Salad','Easy',10,0,2,280,FALSE),
(84,'Chicken Noodle Soup','Classic chicken broth with noodles and vegetables','comfort','Western','Soup','Easy',10,25,4,280,FALSE),
(85,'Beef Pho','Vietnamese bone broth with rice noodles and fresh herbs','healthy','Vietnamese','Soup','Hard',20,180,3,400,TRUE),
(86,'Caesar Salad','Romaine with anchovy dressing, parmesan and croutons','healthy','Western','Salad','Easy',10,0,2,300,FALSE),
(87,'Miso Soup','Light Japanese soup with tofu, seaweed and dashi','healthy','Japanese','Soup','Easy',2,5,2,120,FALSE),
(88,'Gazpacho','Chilled Spanish tomato soup with peppers and cucumber','healthy','Spanish','Soup','Easy',15,0,4,200,FALSE),
(89,'Chocolate Lava Cake','Warm chocolate cake with a gooey molten centre','indulgent','Western','Dessert','Medium',10,12,2,350,TRUE),
(90,'Kheer','Pakistani rice pudding with cardamom and nuts','comfort','Pakistani','Dessert','Easy',5,40,4,200,FALSE),
(91,'Gulab Jamun','Soft milk dumplings soaked in rose-cardamom syrup','indulgent','Pakistani','Dessert','Medium',15,20,6,180,TRUE),
(92,'Mango Kulfi','Creamy frozen mango dessert with pistachio','comfort','Pakistani','Dessert','Easy',10,0,4,200,FALSE),
(93,'Fluffy Pancakes','Stacked pancakes with maple syrup and butter','comfort','Western','Breakfast','Easy',5,15,2,180,FALSE),
(94,'Banana Bread','Moist banana loaf with walnuts and cinnamon','comfort','Western','Dessert','Easy',10,55,8,220,FALSE),
(95,'New York Cheesecake','Creamy cheesecake on a buttery biscuit base','indulgent','Western','Dessert','Hard',20,60,8,600,FALSE),
(96,'Chicken Teriyaki','Grilled chicken glazed with sweet soy teriyaki sauce','healthy','Japanese','Main Course','Easy',5,15,2,380,TRUE),
(97,'Gyoza','Pan-fried pork and cabbage dumplings with dipping sauce','comfort','Japanese','Snack','Medium',20,10,4,300,FALSE),
(98,'Onigiri','Japanese rice balls filled with tuna mayo','healthy','Japanese','Snack','Easy',10,0,2,150,FALSE),
(99,'Yakitori','Grilled chicken skewers glazed with tare sauce','indulgent','Japanese','Snack','Easy',15,10,3,350,FALSE),
(100,'Tonkotsu Ramen','Rich pork bone broth with chashu, soft egg and noodles','comfort','Japanese','Main Course','Hard',20,240,2,500,TRUE);

INSERT INTO recipe_ingredients (recipe_id,ingredient_name,quantity,unit) VALUES
(1,'chicken','700','g'),
(1,'tomatoes','4',''),
(1,'onion','2',''),
(1,'ginger','1','tbsp'),
(1,'garlic','6','cloves'),
(1,'oil','3','tbsp'),
(1,'cumin','1','tsp'),
(1,'coriander powder','1','tsp'),
(1,'red chilli powder','1','tsp'),
(1,'fresh coriander','2','tbsp'),
(2,'yellow lentils','250','g'),
(2,'basmati rice','300','g'),
(2,'onion','1',''),
(2,'tomato','2',''),
(2,'turmeric','0.5','tsp'),
(2,'cumin seeds','1','tsp'),
(2,'ghee','2','tbsp'),
(2,'salt','1','tsp'),
(3,'chicken','1','kg'),
(3,'basmati rice','500','g'),
(3,'onion','3',''),
(3,'yogurt','200','g'),
(3,'ginger-garlic paste','2','tbsp'),
(3,'whole spices','1','tbsp'),
(3,'saffron','1','pinch'),
(3,'oil','4','tbsp'),
(3,'mint','10','leaves'),
(4,'beef shank','700','g'),
(4,'onion','2',''),
(4,'ginger','2','tbsp'),
(4,'garlic','8','cloves'),
(4,'nihari masala','2','tbsp'),
(4,'wheat flour','3','tbsp'),
(4,'oil','4','tbsp'),
(4,'lemon','2',''),
(4,'fresh coriander','3','tbsp'),
(5,'minced beef','400','g'),
(5,'potato','3',''),
(5,'onion','1',''),
(5,'tomato','2',''),
(5,'ginger-garlic paste','1','tbsp'),
(5,'keema masala','1','tbsp'),
(5,'oil','2','tbsp'),
(5,'fresh coriander','2','tbsp'),
(6,'chickpeas','400','g'),
(6,'onion','1',''),
(6,'tomatoes','3',''),
(6,'ginger','1','tbsp'),
(6,'garlic','4','cloves'),
(6,'cumin','1','tsp'),
(6,'coriander powder','1','tsp'),
(6,'garam masala','0.5','tsp'),
(6,'oil','2','tbsp'),
(7,'lamb','500','g'),
(7,'spinach','300','g'),
(7,'onion','1',''),
(7,'tomato','2',''),
(7,'yogurt','100','g'),
(7,'ginger-garlic paste','1','tbsp'),
(7,'garam masala','1','tsp'),
(7,'oil','3','tbsp'),
(8,'beef','400','g'),
(8,'broken wheat','100','g'),
(8,'lentils','100','g'),
(8,'onion','2',''),
(8,'ginger','2','tbsp'),
(8,'haleem masala','2','tbsp'),
(8,'oil','3','tbsp'),
(8,'lemon','2',''),
(8,'fried onions','4','tbsp'),
(9,'whole wheat flour','300','g'),
(9,'potato','3',''),
(9,'green chilli','2',''),
(9,'cumin seeds','1','tsp'),
(9,'coriander','1','tsp'),
(9,'butter','50','g'),
(9,'salt','1','tsp'),
(10,'minced beef','500','g'),
(10,'onion','1',''),
(10,'tomato','2',''),
(10,'pomegranate seeds','2','tbsp'),
(10,'green chilli','3',''),
(10,'coriander','2','tbsp'),
(10,'egg','1',''),
(10,'oil','3','tbsp'),
(11,'chicken','600','g'),
(11,'onion','2',''),
(11,'tomatoes','4',''),
(11,'heavy cream','100','ml'),
(11,'butter','50','g'),
(11,'ginger-garlic paste','2','tbsp'),
(11,'garam masala','1','tsp'),
(11,'kashmiri chilli','1','tsp'),
(11,'honey','1','tsp'),
(12,'paneer','300','g'),
(12,'spinach','400','g'),
(12,'onion','1',''),
(12,'tomato','2',''),
(12,'cream','50','ml'),
(12,'ginger','1','tbsp'),
(12,'garlic','3','cloves'),
(12,'garam masala','1','tsp'),
(12,'oil','2','tbsp'),
(13,'chickpeas','400','g'),
(13,'onion','1',''),
(13,'tomatoes','3',''),
(13,'ginger','1','tbsp'),
(13,'garlic','4','cloves'),
(13,'chole masala','2','tbsp'),
(13,'flour','300','g'),
(13,'yogurt','100','g'),
(13,'oil','4','tbsp'),
(14,'rice batter','400','g'),
(14,'potato','3',''),
(14,'mustard seeds','1','tsp'),
(14,'curry leaves','10',''),
(14,'green chilli','2',''),
(14,'turmeric','0.5','tsp'),
(14,'onion','1',''),
(14,'oil','2','tbsp'),
(15,'kidney beans','400','g'),
(15,'basmati rice','300','g'),
(15,'onion','1',''),
(15,'tomatoes','2',''),
(15,'ginger-garlic paste','1','tbsp'),
(15,'rajma masala','1','tbsp'),
(15,'oil','2','tbsp'),
(15,'cream','2','tbsp'),
(16,'paneer','300','g'),
(16,'yogurt','150','g'),
(16,'lemon','1',''),
(16,'ginger-garlic paste','1','tbsp'),
(16,'tikka masala','2','tbsp'),
(16,'bell pepper','2',''),
(16,'onion','1',''),
(16,'oil','2','tbsp'),
(17,'black lentils','250','g'),
(17,'kidney beans','50','g'),
(17,'butter','60','g'),
(17,'cream','100','ml'),
(17,'tomato puree','100','g'),
(17,'ginger','1','tbsp'),
(17,'garlic','4','cloves'),
(17,'garam masala','1','tsp'),
(18,'cauliflower','1',''),
(18,'potato','2',''),
(18,'onion','1',''),
(18,'tomato','1',''),
(18,'turmeric','0.5','tsp'),
(18,'cumin seeds','1','tsp'),
(18,'coriander powder','1','tsp'),
(18,'oil','3','tbsp'),
(19,'flour','200','g'),
(19,'potato','3',''),
(19,'peas','50','g'),
(19,'cumin seeds','1','tsp'),
(19,'garam masala','1','tsp'),
(19,'green chilli','2',''),
(19,'oil','400','ml'),
(19,'salt','1','tsp'),
(20,'basmati rice','300','g'),
(20,'onion','2',''),
(20,'whole spices','1','tbsp'),
(20,'ghee','3','tbsp'),
(20,'saffron','1','pinch'),
(20,'cashews','30','g'),
(20,'salt','1','tsp'),
(21,'spaghetti','200','g'),
(21,'guanciale','150','g'),
(21,'eggs','3',''),
(21,'pecorino romano','80','g'),
(21,'black pepper','2','tsp'),
(21,'salt','1','tsp'),
(22,'pizza dough','250','g'),
(22,'tomato sauce','100','g'),
(22,'mozzarella','200','g'),
(22,'fresh basil','10','leaves'),
(22,'olive oil','2','tbsp'),
(22,'salt','1','tsp'),
(23,'penne','200','g'),
(23,'chicken','300','g'),
(23,'heavy cream','150','ml'),
(23,'garlic','3','cloves'),
(23,'parmesan','60','g'),
(23,'butter','30','g'),
(23,'salt','1','tsp'),
(23,'black pepper','1','tsp'),
(24,'arborio rice','300','g'),
(24,'mushrooms','200','g'),
(24,'onion','1',''),
(24,'white wine','100','ml'),
(24,'parmesan','80','g'),
(24,'butter','60','g'),
(24,'vegetable stock','800','ml'),
(24,'garlic','2','cloves'),
(25,'baguette','1',''),
(25,'tomatoes','3',''),
(25,'basil','10','leaves'),
(25,'garlic','2','cloves'),
(25,'olive oil','3','tbsp'),
(25,'salt','1','tsp'),
(25,'balsamic vinegar','1','tsp'),
(26,'lasagna sheets','12',''),
(26,'ground beef','400','g'),
(26,'tomato sauce','400','g'),
(26,'bechamel','400','ml'),
(26,'mozzarella','200','g'),
(26,'parmesan','80','g'),
(26,'onion','1',''),
(26,'garlic','3','cloves'),
(27,'pasta','200','g'),
(27,'basil','50','g'),
(27,'pine nuts','30','g'),
(27,'parmesan','60','g'),
(27,'garlic','2','cloves'),
(27,'olive oil','80','ml'),
(27,'salt','1','tsp'),
(28,'mixed vegetables','400','g'),
(28,'canned tomatoes','400','g'),
(28,'pasta','100','g'),
(28,'cannellini beans','200','g'),
(28,'onion','1',''),
(28,'garlic','3','cloves'),
(28,'olive oil','3','tbsp'),
(28,'parmesan','40','g'),
(29,'cooked risotto','400','g'),
(29,'mozzarella','100','g'),
(29,'eggs','2',''),
(29,'breadcrumbs','100','g'),
(29,'flour','50','g'),
(29,'oil','400','ml'),
(30,'ladyfingers','24',''),
(30,'mascarpone','500','g'),
(30,'eggs','4',''),
(30,'sugar','100','g'),
(30,'espresso','200','ml'),
(30,'cocoa powder','2','tbsp'),
(31,'cooked rice','300','g'),
(31,'eggs','2',''),
(31,'spring onions','3',''),
(31,'soy sauce','2','tbsp'),
(31,'sesame oil','1','tbsp'),
(31,'peas','50','g'),
(31,'garlic','2','cloves'),
(31,'oil','2','tbsp'),
(32,'chicken','400','g'),
(32,'peanuts','60','g'),
(32,'dried chillies','8',''),
(32,'sichuan pepper','1','tsp'),
(32,'soy sauce','2','tbsp'),
(32,'rice vinegar','1','tbsp'),
(32,'sugar','1','tsp'),
(32,'garlic','3','cloves'),
(32,'ginger','1','tbsp'),
(33,'minced pork','300','g'),
(33,'cabbage','100','g'),
(33,'soy sauce','1','tbsp'),
(33,'sesame oil','1','tbsp'),
(33,'ginger','1','tbsp'),
(33,'dumpling wrappers','30',''),
(33,'spring onion','2',''),
(34,'chicken','400','g'),
(34,'pineapple','100','g'),
(34,'bell pepper','2',''),
(34,'onion','1',''),
(34,'vinegar','3','tbsp'),
(34,'sugar','3','tbsp'),
(34,'ketchup','3','tbsp'),
(34,'cornstarch','3','tbsp'),
(34,'soy sauce','2','tbsp'),
(35,'tofu','200','g'),
(35,'mushrooms','100','g'),
(35,'bamboo shoots','50','g'),
(35,'egg','1',''),
(35,'vinegar','2','tbsp'),
(35,'soy sauce','2','tbsp'),
(35,'white pepper','1','tsp'),
(35,'cornstarch','2','tbsp'),
(35,'chicken stock','800','ml'),
(36,'noodles','200','g'),
(36,'chicken','200','g'),
(36,'cabbage','100','g'),
(36,'carrot','1',''),
(36,'spring onion','3',''),
(36,'soy sauce','3','tbsp'),
(36,'sesame oil','1','tbsp'),
(36,'oil','2','tbsp'),
(37,'silken tofu','300','g'),
(37,'minced pork','150','g'),
(37,'doubanjiang','2','tbsp'),
(37,'sichuan pepper','1','tsp'),
(37,'garlic','3','cloves'),
(37,'ginger','1','tbsp'),
(37,'soy sauce','1','tbsp'),
(37,'oil','2','tbsp'),
(38,'spring roll wrappers','12',''),
(38,'cabbage','100','g'),
(38,'carrot','1',''),
(38,'glass noodles','50','g'),
(38,'soy sauce','1','tbsp'),
(38,'sesame oil','1','tsp'),
(38,'oil','400','ml'),
(39,'pork belly','500','g'),
(39,'honey','3','tbsp'),
(39,'hoisin sauce','3','tbsp'),
(39,'soy sauce','2','tbsp'),
(39,'five spice','1','tsp'),
(39,'garlic','4','cloves'),
(39,'shaoxing wine','2','tbsp'),
(40,'wonton wrappers','24',''),
(40,'minced pork','200','g'),
(40,'shrimp','100','g'),
(40,'soy sauce','1','tbsp'),
(40,'sesame oil','1','tsp'),
(40,'ginger','1','tbsp'),
(40,'chicken stock','1','L'),
(40,'spring onion','2',''),
(41,'cooked rice','300','g'),
(41,'spinach','50','g'),
(41,'carrot','1',''),
(41,'zucchini','1',''),
(41,'bean sprouts','50','g'),
(41,'egg','1',''),
(41,'gochujang','2','tbsp'),
(41,'sesame oil','1','tbsp'),
(41,'soy sauce','1','tbsp'),
(42,'rice cakes','300','g'),
(42,'gochujang','3','tbsp'),
(42,'sugar','1','tbsp'),
(42,'soy sauce','1','tbsp'),
(42,'fish cake','100','g'),
(42,'spring onion','2',''),
(42,'sesame seeds','1','tsp'),
(43,'chicken','700','g'),
(43,'cornstarch','100','g'),
(43,'flour','50','g'),
(43,'eggs','2',''),
(43,'gochujang','2','tbsp'),
(43,'honey','2','tbsp'),
(43,'soy sauce','2','tbsp'),
(43,'garlic','4','cloves'),
(43,'oil','500','ml'),
(44,'glass noodles','200','g'),
(44,'spinach','100','g'),
(44,'carrot','1',''),
(44,'mushrooms','100','g'),
(44,'egg','1',''),
(44,'soy sauce','3','tbsp'),
(44,'sesame oil','2','tbsp'),
(44,'sugar','1','tsp'),
(44,'sesame seeds','1','tbsp'),
(45,'silken tofu','400','g'),
(45,'kimchi','100','g'),
(45,'clams','100','g'),
(45,'mushrooms','50','g'),
(45,'gochugaru','1','tbsp'),
(45,'garlic','3','cloves'),
(45,'anchovy stock','600','ml'),
(45,'sesame oil','1','tsp'),
(46,'cooked rice','300','g'),
(46,'kimchi','150','g'),
(46,'egg','1',''),
(46,'spam','100','g'),
(46,'sesame oil','1','tbsp'),
(46,'soy sauce','1','tbsp'),
(46,'spring onion','2',''),
(46,'gochujang','1','tbsp'),
(47,'beef short ribs','800','g'),
(47,'soy sauce','4','tbsp'),
(47,'pear','1',''),
(47,'garlic','6','cloves'),
(47,'ginger','1','tbsp'),
(47,'sesame oil','2','tbsp'),
(47,'sugar','2','tbsp'),
(47,'spring onion','3',''),
(48,'flour','150','g'),
(48,'egg','1',''),
(48,'spring onion','5',''),
(48,'squid','100','g'),
(48,'shrimp','50','g'),
(48,'soy sauce','2','tbsp'),
(48,'rice vinegar','1','tbsp'),
(48,'sesame oil','1','tsp'),
(48,'oil','3','tbsp'),
(49,'doenjang paste','2','tbsp'),
(49,'tofu','200','g'),
(49,'zucchini','1',''),
(49,'mushrooms','50','g'),
(49,'garlic','2','cloves'),
(49,'anchovy stock','600','ml'),
(49,'spring onion','2',''),
(49,'sesame oil','1','tsp'),
(50,'instant noodles','1','packet'),
(50,'egg','1',''),
(50,'spam','50','g'),
(50,'spring onion','1',''),
(50,'gochugaru','1','tsp'),
(50,'water','400','ml'),
(51,'chicken','400','g'),
(51,'tikka masala','2','tbsp'),
(51,'yogurt','100','g'),
(51,'tortillas','6',''),
(51,'raita','100','g'),
(51,'onion','1',''),
(51,'lemon','1',''),
(51,'coriander','2','tbsp'),
(52,'ground beef','300','g'),
(52,'soy sauce','2','tbsp'),
(52,'pear','0.5',''),
(52,'garlic','3','cloves'),
(52,'sesame oil','1','tbsp'),
(52,'kimchi','100','g'),
(52,'gochujang mayo','3','tbsp'),
(52,'burger buns','2',''),
(53,'macaroni','200','g'),
(53,'cheddar','200','g'),
(53,'milk','300','ml'),
(53,'butter','30','g'),
(53,'flour','2','tbsp'),
(53,'cumin','1','tsp'),
(53,'garam masala','1','tsp'),
(53,'green chilli','2',''),
(53,'tomato','1',''),
(54,'sushi rice','300','g'),
(54,'salmon','200','g'),
(54,'avocado','1',''),
(54,'cucumber','1',''),
(54,'nori sheets','3',''),
(54,'rice vinegar','2','tbsp'),
(54,'soy sauce','2','tbsp'),
(54,'sriracha','1','tbsp'),
(55,'chicken','300','g'),
(55,'tandoori masala','2','tbsp'),
(55,'yogurt','100','g'),
(55,'tortillas','4',''),
(55,'mozzarella','150','g'),
(55,'butter','20','g'),
(56,'ramen noodles','200','g'),
(56,'eggs','3',''),
(56,'pecorino','60','g'),
(56,'guanciale','100','g'),
(56,'black pepper','1','tsp'),
(56,'miso paste','1','tsp'),
(57,'mango','2',''),
(57,'avocado','1',''),
(57,'red onion','0.5',''),
(57,'lime','1',''),
(57,'chilli flakes','0.5','tsp'),
(57,'coriander','2','tbsp'),
(57,'olive oil','2','tbsp'),
(57,'salt','0.5','tsp'),
(58,'sourdough','2','slices'),
(58,'kimchi','80','g'),
(58,'cheddar','80','g'),
(58,'gruyere','40','g'),
(58,'butter','20','g'),
(58,'mayonnaise','1','tbsp'),
(59,'chicken','600','g'),
(59,'peri peri sauce','3','tbsp'),
(59,'basmati rice','400','g'),
(59,'onion','2',''),
(59,'whole spices','1','tbsp'),
(59,'yogurt','100','g'),
(59,'saffron','1','pinch'),
(59,'oil','4','tbsp'),
(60,'chicken','400','g'),
(60,'tikka masala','2','tbsp'),
(60,'coconut milk','200','ml'),
(60,'peanut butter','3','tbsp'),
(60,'noodles','200','g'),
(60,'lime','1',''),
(60,'coriander','2','tbsp'),
(60,'spring onion','3',''),
(61,'sourdough bread','2','slices'),
(61,'avocado','1',''),
(61,'lemon','0.5',''),
(61,'chilli flakes','0.5','tsp'),
(61,'salt','0.5','tsp'),
(61,'olive oil','1','tbsp'),
(62,'eggs','2',''),
(62,'cheddar','50','g'),
(62,'butter','10','g'),
(62,'chives','1','tbsp'),
(62,'salt','0.5','tsp'),
(62,'black pepper','0.5','tsp'),
(63,'baguette','1',''),
(63,'butter','80','g'),
(63,'garlic','4','cloves'),
(63,'parsley','2','tbsp'),
(63,'salt','0.5','tsp'),
(64,'tortilla chips','200','g'),
(64,'cheddar','150','g'),
(64,'jalapenos','3',''),
(64,'salsa','100','g'),
(64,'sour cream','50','g'),
(64,'guacamole','100','g'),
(65,'eggs','2',''),
(65,'bread','2','slices'),
(65,'butter','10','g'),
(65,'salt','0.5','tsp'),
(65,'black pepper','0.5','tsp'),
(66,'banana','2',''),
(66,'yogurt','150','g'),
(66,'oats','3','tbsp'),
(66,'honey','1','tbsp'),
(66,'milk','100','ml'),
(67,'flour tortillas','2',''),
(67,'cheddar','100','g'),
(67,'bell pepper','1',''),
(67,'onion','0.5',''),
(67,'butter','15','g'),
(67,'sour cream','50','g'),
(68,'bread','2','slices'),
(68,'peanut butter','3','tbsp'),
(68,'banana','1',''),
(68,'honey','1','tsp'),
(69,'whole wheat flour','300','g'),
(69,'water','150','ml'),
(69,'oil','3','tbsp'),
(69,'salt','1','tsp'),
(69,'chai tea','2','cups'),
(70,'flour','200','g'),
(70,'potato','3',''),
(70,'peas','80','g'),
(70,'cumin seeds','1','tsp'),
(70,'garam masala','1','tsp'),
(70,'green chilli','3',''),
(70,'oil','400','ml'),
(70,'coriander','2','tbsp'),
(71,'ribeye steak','400','g'),
(71,'butter','60','g'),
(71,'garlic','4','cloves'),
(71,'rosemary','2','sprigs'),
(71,'thyme','2','sprigs'),
(71,'salt','1','tsp'),
(71,'black pepper','1','tsp'),
(72,'salmon fillet','400','g'),
(72,'lemon','1',''),
(72,'dill','2','tbsp'),
(72,'olive oil','2','tbsp'),
(72,'garlic','2','cloves'),
(72,'salt','1','tsp'),
(72,'black pepper','1','tsp'),
(73,'romaine lettuce','1',''),
(73,'chicken breast','300','g'),
(73,'croutons','50','g'),
(73,'parmesan','60','g'),
(73,'caesar dressing','80','ml'),
(73,'black pepper','0.5','tsp'),
(74,'lamb chops','600','g'),
(74,'garlic','4','cloves'),
(74,'rosemary','2','tbsp'),
(74,'olive oil','3','tbsp'),
(74,'lemon','1',''),
(74,'salt','1','tsp'),
(74,'black pepper','1','tsp'),
(75,'chicken pieces','700','g'),
(75,'BBQ sauce','150','g'),
(75,'garlic powder','1','tsp'),
(75,'paprika','1','tsp'),
(75,'oil','2','tbsp'),
(75,'salt','1','tsp'),
(76,'white fish','400','g'),
(76,'beer','150','ml'),
(76,'flour','150','g'),
(76,'baking powder','1','tsp'),
(76,'potato','4',''),
(76,'oil','500','ml'),
(76,'salt','1','tsp'),
(76,'vinegar','2','tbsp'),
(77,'ground beef','400','g'),
(77,'taco shells','8',''),
(77,'taco seasoning','2','tbsp'),
(77,'cheese','100','g'),
(77,'lettuce','50','g'),
(77,'tomato','2',''),
(77,'sour cream','80','g'),
(77,'salsa','80','g'),
(78,'chicken','500','g'),
(78,'yogurt','150','g'),
(78,'shawarma spice','2','tbsp'),
(78,'garlic','4','cloves'),
(78,'lemon','1',''),
(78,'flatbread','4',''),
(78,'garlic sauce','80','g'),
(78,'tomato','2',''),
(78,'onion','1',''),
(79,'lamb','600','g'),
(79,'yogurt','200','g'),
(79,'almonds','50','g'),
(79,'onion','2',''),
(79,'ginger-garlic paste','2','tbsp'),
(79,'whole spices','1','tbsp'),
(79,'cream','100','ml'),
(79,'saffron','1','pinch'),
(79,'oil','3','tbsp'),
(80,'chicken','400','g'),
(80,'coconut milk','400','ml'),
(80,'green curry paste','3','tbsp'),
(80,'thai basil','20','leaves'),
(80,'fish sauce','2','tbsp'),
(80,'sugar','1','tsp'),
(80,'lime','1',''),
(80,'jasmine rice','300','g'),
(81,'tomatoes','800','g'),
(81,'onion','1',''),
(81,'garlic','3','cloves'),
(81,'basil','20','leaves'),
(81,'cream','100','ml'),
(81,'olive oil','3','tbsp'),
(81,'sugar','1','tsp'),
(81,'chicken stock','300','ml'),
(82,'red lentils','300','g'),
(82,'onion','1',''),
(82,'tomato','2',''),
(82,'garlic','3','cloves'),
(82,'cumin','1','tsp'),
(82,'turmeric','0.5','tsp'),
(82,'lemon','1',''),
(82,'olive oil','2','tbsp'),
(82,'chicken stock','1','L'),
(83,'cucumber','1',''),
(83,'tomatoes','3',''),
(83,'red onion','0.5',''),
(83,'olives','80','g'),
(83,'feta','150','g'),
(83,'olive oil','3','tbsp'),
(83,'lemon','1',''),
(83,'oregano','1','tsp'),
(84,'chicken','300','g'),
(84,'noodles','150','g'),
(84,'carrot','2',''),
(84,'celery','3',''),
(84,'onion','1',''),
(84,'chicken stock','1.5','L'),
(84,'thyme','1','tsp'),
(84,'bay leaf','2',''),
(84,'salt','1','tsp'),
(85,'beef bones','1','kg'),
(85,'rice noodles','400','g'),
(85,'star anise','3',''),
(85,'cinnamon','1','stick'),
(85,'ginger','4','slices'),
(85,'fish sauce','2','tbsp'),
(85,'bean sprouts','100','g'),
(85,'basil','20','leaves'),
(85,'lime','2',''),
(85,'hoisin sauce','2','tbsp'),
(86,'romaine lettuce','1',''),
(86,'parmesan','60','g'),
(86,'croutons','50','g'),
(86,'anchovy','4',''),
(86,'garlic','1','clove'),
(86,'lemon','1',''),
(86,'egg yolk','1',''),
(86,'olive oil','80','ml'),
(86,'worcestershire sauce','1','tsp'),
(87,'dashi stock','600','ml'),
(87,'miso paste','2','tbsp'),
(87,'silken tofu','150','g'),
(87,'wakame seaweed','1','tbsp'),
(87,'spring onion','2',''),
(88,'tomatoes','600','g'),
(88,'cucumber','1',''),
(88,'red pepper','1',''),
(88,'onion','0.5',''),
(88,'garlic','2','cloves'),
(88,'olive oil','3','tbsp'),
(88,'vinegar','2','tbsp'),
(88,'salt','1','tsp'),
(89,'dark chocolate','150','g'),
(89,'butter','100','g'),
(89,'eggs','3',''),
(89,'sugar','80','g'),
(89,'flour','40','g'),
(89,'cocoa powder','1','tbsp'),
(89,'vanilla','1','tsp'),
(89,'salt','0.5','tsp'),
(90,'basmati rice','150','g'),
(90,'whole milk','1','L'),
(90,'sugar','80','g'),
(90,'cardamom','4','pods'),
(90,'saffron','1','pinch'),
(90,'almonds','30','g'),
(90,'pistachios','20','g'),
(90,'rose water','1','tsp'),
(91,'milk powder','200','g'),
(91,'flour','2','tbsp'),
(91,'baking soda','0.25','tsp'),
(91,'ghee','1','tbsp'),
(91,'milk','4','tbsp'),
(91,'sugar','300','g'),
(91,'water','300','ml'),
(91,'cardamom','4','pods'),
(91,'rose water','1','tsp'),
(91,'oil','400','ml'),
(92,'mango puree','300','g'),
(92,'condensed milk','200','g'),
(92,'heavy cream','200','ml'),
(92,'cardamom','0.5','tsp'),
(92,'pistachios','30','g'),
(92,'kulfi moulds','4',''),
(93,'flour','200','g'),
(93,'baking powder','2','tsp'),
(93,'sugar','2','tbsp'),
(93,'eggs','2',''),
(93,'milk','250','ml'),
(93,'butter','50','g'),
(93,'vanilla','1','tsp'),
(93,'salt','0.5','tsp'),
(94,'ripe bananas','3',''),
(94,'flour','200','g'),
(94,'sugar','150','g'),
(94,'eggs','2',''),
(94,'butter','80','g'),
(94,'baking soda','1','tsp'),
(94,'walnuts','80','g'),
(94,'cinnamon','1','tsp'),
(94,'vanilla','1','tsp'),
(95,'digestive biscuits','200','g'),
(95,'butter','80','g'),
(95,'cream cheese','600','g'),
(95,'sugar','150','g'),
(95,'eggs','3',''),
(95,'sour cream','150','g'),
(95,'vanilla','1','tsp'),
(95,'lemon','1',''),
(96,'chicken thighs','400','g'),
(96,'soy sauce','4','tbsp'),
(96,'mirin','3','tbsp'),
(96,'sake','2','tbsp'),
(96,'sugar','2','tbsp'),
(96,'garlic','2','cloves'),
(96,'ginger','1','tsp'),
(96,'sesame seeds','1','tbsp'),
(97,'minced pork','200','g'),
(97,'cabbage','100','g'),
(97,'gyoza wrappers','20',''),
(97,'garlic','2','cloves'),
(97,'ginger','1','tbsp'),
(97,'soy sauce','1','tbsp'),
(97,'sesame oil','1','tbsp'),
(97,'dipping sauce','3','tbsp'),
(98,'sushi rice','250','g'),
(98,'tuna in mayo','100','g'),
(98,'nori sheets','3',''),
(98,'sesame seeds','1','tbsp'),
(98,'soy sauce','2','tbsp'),
(98,'rice vinegar','2','tbsp'),
(98,'salt','0.5','tsp'),
(99,'chicken thighs','400','g'),
(99,'soy sauce','3','tbsp'),
(99,'mirin','2','tbsp'),
(99,'sake','1','tbsp'),
(99,'sugar','1','tbsp'),
(99,'spring onion','3',''),
(99,'skewers','10',''),
(100,'pork belly','300','g'),
(100,'ramen noodles','200','g'),
(100,'soft-boiled eggs','2',''),
(100,'nori','2','sheets'),
(100,'spring onion','3',''),
(100,'bamboo shoots','50','g'),
(100,'corn','50','g'),
(100,'sesame oil','1','tbsp'),
(100,'soy sauce','2','tbsp'),
(100,'chicken stock','1','L');

INSERT INTO recipe_steps (recipe_id,step_number,instruction) VALUES
(1,1,'Heat oil in a karahi or wok over high heat. Add onions and fry until golden brown.'),
(1,2,'Add ginger-garlic paste and fry for 2 minutes until fragrant.'),
(1,3,'Add chicken pieces and sear on high heat for 5 minutes.'),
(1,4,'Add tomatoes, cumin, coriander powder, red chilli powder and salt. Mix well.'),
(1,5,'Cover and cook on medium heat for 20 minutes, stirring occasionally.'),
(1,6,'Uncover and cook on high heat for 5 minutes until oil separates.'),
(1,7,'Garnish with fresh coriander and green chillies. Serve with naan.'),
(2,1,'Wash lentils and soak for 10 minutes. Drain.'),
(2,2,'Boil lentils in 700ml water with turmeric and salt for 20 minutes until soft.'),
(2,3,'Mash lentils lightly with a spoon.'),
(2,4,'Heat ghee in a pan. Add cumin seeds and let them splutter.'),
(2,5,'Add chopped onion, fry until golden. Add tomatoes and cook until soft.'),
(2,6,'Pour the tarka over the lentils and stir. Adjust seasoning.'),
(2,7,'Wash basmati rice and cook separately. Serve dal over rice.'),
(3,1,'Marinate chicken in yogurt, ginger-garlic paste, biryani masala, salt and oil for at least 2 hours.'),
(3,2,'Parboil basmati rice until 70% cooked. Drain and set aside.'),
(3,3,'Fry sliced onions in oil until deep golden and crispy. Remove half for garnish.'),
(3,4,'In the same oil, cook marinated chicken until nearly done, about 20 minutes.'),
(3,5,'Layer half the rice over the chicken. Add saffron milk, mint and fried onions.'),
(3,6,'Layer remaining rice on top. Seal the pot with foil and a tight lid.'),
(3,7,'Cook on low heat (dum) for 25 minutes. Gently mix before serving.'),
(4,1,'Slow-cook beef shank in water with ginger, garlic, onion and salt for 2.5 hours.'),
(4,2,'Mix nihari masala with wheat flour and a little water to make a paste.'),
(4,3,'Add the masala paste to the pot. Stir vigorously to avoid lumps.'),
(4,4,'Simmer uncovered for 30 minutes until gravy thickens.'),
(4,5,'Heat oil separately, fry thinly sliced onion until golden, add to nihari.'),
(4,6,'Serve garnished with lemon, green chillies and fresh ginger julienne.'),
(5,1,'Heat oil in a pan. Add finely chopped onion and fry until light golden.'),
(5,2,'Add ginger-garlic paste and fry for 1 minute.'),
(5,3,'Add minced beef and cook on high heat, breaking up lumps, for 8 minutes.'),
(5,4,'Add tomatoes, keema masala, red chilli and salt. Mix well.'),
(5,5,'Add cubed potatoes and 100ml water. Cover and cook for 15 minutes.'),
(5,6,'Cook uncovered until water evaporates and oil separates. Garnish with coriander.'),
(6,1,'Heat oil, add cumin seeds and a bay leaf. Fry for 30 seconds.'),
(6,2,'Add finely diced onion and cook until golden brown.'),
(6,3,'Add ginger and garlic, fry for 1 minute. Add tomatoes and cook until pulpy.'),
(6,4,'Add coriander powder, cumin powder, chilli powder and garam masala.'),
(6,5,'Add drained chickpeas and 200ml water. Simmer for 20 minutes.'),
(6,6,'Mash a few chickpeas with the back of a spoon for a thicker gravy.'),
(6,7,'Squeeze in lemon juice, garnish with coriander and serve with bhature or rice.'),
(7,1,'Blanch spinach in boiling water for 2 minutes. Drain and blend to a smooth puree.'),
(7,2,'Brown lamb pieces in oil on high heat. Remove and set aside.'),
(7,3,'In the same pan, fry onion until golden. Add ginger-garlic paste.'),
(7,4,'Add tomatoes, garam masala, chilli and salt. Cook until oil separates.'),
(7,5,'Return lamb to pan. Add 200ml water, cover and simmer for 35 minutes.'),
(7,6,'Stir in spinach puree and yogurt. Simmer for 10 more minutes.'),
(7,7,'Finish with a swirl of cream. Serve with naan.'),
(8,1,'Pressure cook beef with ginger, garlic, onion and salt for 45 minutes.'),
(8,2,'Add soaked broken wheat and lentils. Pressure cook for 20 more minutes.'),
(8,3,'Using a masher or blender, break down the mixture until thick and porridge-like.'),
(8,4,'Heat oil in a pan, fry onion until deep brown. Add haleem masala, fry 2 minutes.'),
(8,5,'Combine the tarka with the haleem mixture. Simmer for 15 minutes, stirring often.'),
(8,6,'Serve topped with fried onions, lemon juice, ginger julienne and green chillies.'),
(9,1,'Knead flour with water, salt and a little oil into a soft dough. Rest 20 minutes.'),
(9,2,'Boil potatoes until soft. Mash with salt, cumin, green chilli, coriander and ajwain.'),
(9,3,'Divide dough into balls. Roll each into a small circle.'),
(9,4,'Place a spoonful of filling in the centre. Seal edges and roll out into a paratha.'),
(9,5,'Cook on a hot tawa with butter on both sides until golden and crispy.'),
(9,6,'Serve hot with yogurt or pickle.'),
(10,1,'Mix minced beef with finely chopped onion, tomato, green chilli, coriander and egg.'),
(10,2,'Add pomegranate seeds, cumin powder, coriander powder and salt. Mix well.'),
(10,3,'Wet hands and flatten a portion of the mixture into a thin patty.'),
(10,4,'Heat oil in a heavy pan. Shallow fry kebabs on medium heat for 4 minutes per side.'),
(10,5,'Serve with naan, sliced onions, lemon and chutney.'),
(11,1,'Marinate chicken in yogurt, ginger-garlic paste, kashmiri chilli and salt for 30 minutes.'),
(11,2,'Heat butter in a pan. Cook the marinated chicken until browned. Remove and set aside.'),
(11,3,'In the same pan, fry onion until golden. Add ginger-garlic paste.'),
(11,4,'Add tomato puree and cook for 10 minutes. Add kashmiri chilli, garam masala and salt.'),
(11,5,'Blend the sauce until smooth. Return to pan and add cream.'),
(11,6,'Add the cooked chicken and simmer for 10 minutes. Finish with butter.'),
(11,7,'Garnish with cream swirl and coriander. Serve with naan.'),
(12,1,'Blanch spinach, blend to a smooth puree.'),
(12,2,'Fry paneer cubes in a little oil until golden. Remove and set aside.'),
(12,3,'Saute onion until translucent. Add ginger, garlic, tomato and cook until soft.'),
(12,4,'Add spices: garam masala, cumin, coriander. Cook for 2 minutes.'),
(12,5,'Add spinach puree and simmer for 5 minutes.'),
(12,6,'Stir in cream and the fried paneer. Simmer for 5 more minutes. Serve hot.'),
(13,1,'Soak chickpeas overnight. Pressure cook until soft.'),
(13,2,'Saute onion, ginger and garlic in oil until golden.'),
(13,3,'Add tomatoes and chole masala. Cook until oil separates.'),
(13,4,'Add chickpeas and 200ml water. Simmer for 15 minutes. Mash a few chickpeas.'),
(13,5,'For bhature: knead flour with yogurt, baking soda and water. Rest 2 hours.'),
(13,6,'Roll bhature and deep fry until puffed and golden. Serve with chole.'),
(14,1,'Heat a non-stick pan. Pour a ladle of rice batter and spread into a thin circle.'),
(14,2,'Cook until edges lift and the crepe is crispy. Drizzle oil around edges.'),
(14,3,'For filling: heat oil, add mustard seeds, curry leaves, onion and potato.'),
(14,4,'Season with turmeric, salt and green chilli. Cook until potatoes are soft.'),
(14,5,'Place filling on one half of the dosa. Fold and serve with coconut chutney and sambar.'),
(15,1,'Soak kidney beans overnight. Pressure cook for 25 minutes until soft.'),
(15,2,'Heat oil, fry onion until golden. Add ginger-garlic paste.'),
(15,3,'Add tomatoes and rajma masala. Cook until oil separates.'),
(15,4,'Add cooked kidney beans with their liquid. Simmer for 20 minutes.'),
(15,5,'Mash a few beans for thickness. Finish with cream. Serve over steamed rice.'),
(16,1,'Mix yogurt, tikka masala, lemon juice, ginger-garlic paste and salt.'),
(16,2,'Marinate paneer and vegetables in the mixture for 1 hour.'),
(16,3,'Thread onto skewers and grill or bake at 220C for 12 minutes.'),
(16,4,'Brush with butter and grill for 2 more minutes until lightly charred.'),
(16,5,'Serve with mint chutney and lemon wedges.'),
(17,1,'Soak black lentils overnight. Drain.'),
(17,2,'Pressure cook lentils with kidney beans for 45 minutes.'),
(17,3,'Mash lightly. Saute garlic and ginger in butter.'),
(17,4,'Add tomato puree, red chilli and garam masala. Cook for 10 minutes.'),
(17,5,'Combine with lentils. Simmer on very low heat for 30 minutes, stirring occasionally.'),
(17,6,'Stir in cream and butter. Simmer for 10 more minutes. Serve with naan.'),
(18,1,'Heat oil in a wide pan. Add cumin seeds and let them splutter.'),
(18,2,'Add chopped onion and fry until translucent.'),
(18,3,'Add tomato, turmeric, coriander powder and chilli powder. Cook until soft.'),
(18,4,'Add cauliflower and potato. Stir to coat with spices.'),
(18,5,'Cover and cook on low heat for 15 minutes until vegetables are tender.'),
(18,6,'Uncover and cook on high heat for 3 minutes. Garnish with coriander.'),
(19,1,'Make a stiff dough with flour, salt and oil. Divide into balls.'),
(19,2,'Boil and mash potatoes with peas, cumin, garam masala, green chilli and coriander.'),
(19,3,'Roll each dough ball into an oval. Cut in half to make two triangles.'),
(19,4,'Fill each triangle with potato mixture. Seal edges with water.'),
(19,5,'Deep fry in medium-hot oil until golden and crispy.'),
(19,6,'Serve with mint chutney and tamarind sauce.'),
(20,1,'Wash basmati rice and soak for 20 minutes. Drain.'),
(20,2,'Heat ghee in a pot. Fry whole spices until fragrant.'),
(20,3,'Add thinly sliced onion and fry until golden.'),
(20,4,'Add drained rice and stir gently to coat in ghee.'),
(20,5,'Add hot water (ratio 1:1.5 rice to water), salt and saffron milk.'),
(20,6,'Cover tightly and cook on low heat for 15 minutes. Fluff and serve.'),
(21,1,'Cook spaghetti in heavily salted boiling water until al dente.'),
(21,2,'Fry guanciale in a dry pan over medium heat until fat renders and edges crisp.'),
(21,3,'Whisk eggs with finely grated pecorino and a generous amount of black pepper.'),
(21,4,'Reserve a mug of pasta water. Drain pasta.'),
(21,5,'Remove guanciale pan from heat. Add hot pasta and toss to coat.'),
(21,6,'Pour egg mixture over pasta, tossing quickly. Add pasta water gradually to create a silky sauce.'),
(21,7,'Serve immediately with extra pecorino and black pepper.'),
(22,1,'Stretch pizza dough into a thin round.'),
(22,2,'Spread tomato sauce evenly, leaving a 2cm border.'),
(22,3,'Tear mozzarella and distribute evenly.'),
(22,4,'Bake in a preheated oven at 250C for 10-12 minutes until crust is golden.'),
(22,5,'Top with fresh basil leaves and a drizzle of olive oil. Serve immediately.'),
(23,1,'Season and grill chicken breast. Slice into strips.'),
(23,2,'Cook penne in salted boiling water until al dente.'),
(23,3,'In a pan, saute garlic in butter. Pour in cream and simmer for 3 minutes.'),
(23,4,'Add grated parmesan and stir until melted into the sauce.'),
(23,5,'Toss in drained pasta and chicken. Season and serve.'),
(24,1,'Heat stock and keep warm. Saute shallots in butter until soft.'),
(24,2,'Add arborio rice and toast for 2 minutes, stirring constantly.'),
(24,3,'Add white wine and stir until absorbed.'),
(24,4,'Add warm stock one ladle at a time, stirring after each addition.'),
(24,5,'After 25 minutes the rice should be creamy and al dente.'),
(24,6,'Remove from heat. Stir in cold butter and parmesan. Serve immediately.'),
(25,1,'Slice baguette diagonally. Brush with olive oil.'),
(25,2,'Toast under the grill or in a griddle pan until golden.'),
(25,3,'Rub each slice with a halved garlic clove.'),
(25,4,'Mix diced tomatoes with basil, olive oil, balsamic and salt.'),
(25,5,'Spoon tomato mixture onto each toast. Serve immediately.'),
(26,1,'Make Bolognese: brown beef with onion and garlic. Add tomato sauce. Simmer 30 min.'),
(26,2,'Make bechamel: melt butter, whisk in flour, gradually add milk. Season.'),
(26,3,'Layer lasagna: sauce, pasta sheets, bechamel, cheese. Repeat 3 times.'),
(26,4,'Top with bechamel and generous parmesan.'),
(26,5,'Bake covered at 180C for 40 minutes. Uncover for last 15 minutes.'),
(27,1,'Blend basil, pine nuts, garlic, parmesan and olive oil until smooth. Season.'),
(27,2,'Cook pasta until al dente. Reserve 100ml pasta water.'),
(27,3,'Toss hot pasta with pesto. Add pasta water to loosen.'),
(27,4,'Serve with extra parmesan and a few torn basil leaves.'),
(28,1,'Saute onion, garlic, carrot and celery in olive oil for 5 minutes.'),
(28,2,'Add canned tomatoes, beans and stock. Bring to a boil.'),
(28,3,'Add pasta and cook for the time specified on the packet.'),
(28,4,'Season and finish with a drizzle of olive oil and parmesan.'),
(29,1,'Let cooked risotto cool. Mix in beaten egg and extra parmesan.'),
(29,2,'Form into balls with a cube of mozzarella in the centre.'),
(29,3,'Coat each ball in flour, egg wash and breadcrumbs.'),
(29,4,'Deep fry at 180C for 4 minutes until golden. Drain and serve immediately.'),
(30,1,'Brew strong espresso and let cool. Mix with a splash of rum.'),
(30,2,'Whisk egg yolks and sugar until pale and ribbony.'),
(30,3,'Fold in mascarpone until smooth.'),
(30,4,'Whip cream to soft peaks and fold into mascarpone mixture.'),
(30,5,'Dip ladyfingers briefly in espresso and layer in a dish.'),
(30,6,'Spread half the cream, add another layer of soaked ladyfingers.'),
(30,7,'Top with remaining cream. Refrigerate overnight. Dust with cocoa before serving.'),
(31,1,'Heat wok over high heat until smoking.'),
(31,2,'Scramble eggs in a little oil, break into pieces and set aside.'),
(31,3,'Fry garlic and spring onion whites for 30 seconds.'),
(31,4,'Add cold cooked rice. Spread and press to get some charring.'),
(31,5,'Add soy sauce and sesame oil. Toss everything together.'),
(31,6,'Add scrambled eggs and peas. Toss briefly. Garnish with spring onion greens.'),
(32,1,'Marinate diced chicken in soy sauce, cornstarch and oil for 15 minutes.'),
(32,2,'Make sauce: mix soy sauce, rice vinegar, sugar, cornstarch and a little water.'),
(32,3,'Stir-fry dried chillies and Sichuan pepper in hot oil for 30 seconds.'),
(32,4,'Add chicken and stir-fry until cooked through.'),
(32,5,'Add garlic, ginger and spring onions. Stir-fry for 1 minute.'),
(32,6,'Pour sauce over and toss until glossy. Add peanuts and serve.'),
(33,1,'Mix minced pork with chopped cabbage, soy sauce, sesame oil, ginger and spring onion.'),
(33,2,'Place a teaspoon of filling in the centre of each wrapper.'),
(33,3,'Wet the edges and pleat to seal.'),
(33,4,'Steam over boiling water for 15 minutes.'),
(33,5,'Serve with soy sauce, rice vinegar and chilli oil dipping sauce.'),
(34,1,'Cut chicken into chunks. Season and coat in cornstarch and egg.'),
(34,2,'Deep fry chicken until golden. Drain on paper towels.'),
(34,3,'Mix ketchup, vinegar, sugar, soy sauce and pineapple juice for the sauce.'),
(34,4,'Stir-fry bell peppers and onion in a little oil.'),
(34,5,'Add sauce and bring to a boil. Add fried chicken and toss until coated.'),
(35,1,'Bring chicken stock to a boil. Add soy sauce, vinegar, white pepper.'),
(35,2,'Add thinly sliced mushrooms and bamboo shoots. Simmer 5 minutes.'),
(35,3,'Mix cornstarch with cold water. Stir into soup to thicken.'),
(35,4,'Drizzle in beaten egg while stirring to create egg ribbons.'),
(35,5,'Add tofu cubes. Serve topped with sesame oil and spring onions.'),
(36,1,'Boil noodles until just tender. Drain.'),
(36,2,'Stir-fry sliced chicken in a hot wok until cooked. Remove.'),
(36,3,'Stir-fry vegetables until tender-crisp.'),
(36,4,'Add noodles, soy sauce, oyster sauce and sesame oil.'),
(36,5,'Return chicken to wok. Toss everything together and serve.'),
(37,1,'Fry minced pork with doubanjiang over medium heat for 3 minutes.'),
(37,2,'Add garlic and ginger. Fry for 1 minute.'),
(37,3,'Add stock and bring to a simmer.'),
(37,4,'Slide in tofu cut into cubes. Simmer gently for 5 minutes.'),
(37,5,'Stir in cornstarch slurry to thicken. Finish with Sichuan pepper and sesame oil.'),
(38,1,'Soak glass noodles until soft. Drain and chop.'),
(38,2,'Mix with shredded cabbage, carrot, soy sauce and sesame oil.'),
(38,3,'Place filling in the centre of each wrapper. Fold and roll, sealing with water.'),
(38,4,'Deep fry in oil at 180C until golden and crispy.'),
(38,5,'Serve with sweet chilli dipping sauce.'),
(39,1,'Mix honey, hoisin sauce, soy sauce, shaoxing wine, five spice and garlic.'),
(39,2,'Score pork belly and marinate in the mixture for at least 4 hours.'),
(39,3,'Roast at 200C for 25 minutes. Brush with more glaze.'),
(39,4,'Roast for another 15 minutes until caramelised and slightly charred at edges.'),
(39,5,'Rest for 10 minutes. Slice and serve with steamed rice.'),
(40,1,'Mix minced pork and shrimp with soy sauce, sesame oil and ginger.'),
(40,2,'Place a teaspoon of filling on each wrapper. Fold into wontons.'),
(40,3,'Bring chicken stock to a simmer with ginger and spring onions.'),
(40,4,'Cook wontons in the broth for 5 minutes until they float.'),
(40,5,'Serve in bowls with broth, topped with spring onions and sesame oil.'),
(41,1,'Cook rice and set aside. Blanch spinach and squeeze out water.'),
(41,2,'Fry carrot, zucchini and bean sprouts separately in sesame oil with a pinch of salt.'),
(41,3,'Fry an egg sunny-side up.'),
(41,4,'Place rice in a warm stone bowl. Arrange all toppings in sections.'),
(41,5,'Place fried egg on top. Add a big spoonful of gochujang.'),
(41,6,'Mix everything vigorously before eating.'),
(42,1,'Soak rice cakes in cold water for 10 minutes if using dried ones.'),
(42,2,'Mix gochujang, sugar, soy sauce and 400ml water in a wide pan.'),
(42,3,'Bring sauce to a boil. Add rice cakes and fish cakes.'),
(42,4,'Cook on medium heat for 10 minutes, stirring often, until sauce thickens.'),
(42,5,'Garnish with spring onions and sesame seeds. Serve immediately.'),
(43,1,'Marinate chicken in yogurt, salt and pepper for 30 minutes.'),
(43,2,'Coat in a mixture of cornstarch and flour. Deep fry at 170C for 8 minutes.'),
(43,3,'Drain. Fry again at 190C for 3 minutes for extra crispiness.'),
(43,4,'Make glaze: mix gochujang, honey, soy sauce, garlic and a little oil in a pan.'),
(43,5,'Toss fried chicken in the glaze. Garnish with sesame seeds and spring onions.'),
(44,1,'Soak glass noodles in warm water for 20 minutes. Drain.'),
(44,2,'Blanch spinach briefly. Squeeze out water and season with sesame oil and soy sauce.'),
(44,3,'Fry carrot and mushroom in sesame oil separately. Season each.'),
(44,4,'Stir-fry noodles with soy sauce, sugar, sesame oil and garlic.'),
(44,5,'Mix noodles with all prepared vegetables. Add a fried egg on top. Toss before eating.'),
(45,1,'Bring anchovy stock to a boil. Add garlic and gochugaru.'),
(45,2,'Add kimchi and simmer for 5 minutes.'),
(45,3,'Gently slide in soft tofu broken into large pieces.'),
(45,4,'Add clams. Cover and cook until clams open.'),
(45,5,'Crack an egg into the stew. Serve immediately with rice.'),
(46,1,'Fry spam or leftover meat in a little oil until lightly browned. Remove.'),
(46,2,'Fry kimchi in the same pan for 3 minutes until fragrant.'),
(46,3,'Add cold cooked rice. Mix and press to get some caramelisation.'),
(46,4,'Add soy sauce, gochujang and sesame oil. Stir well.'),
(46,5,'Make a well and fry an egg in the centre. Serve topped with spring onions.'),
(47,1,'Score beef ribs. Mix soy sauce, blended pear, garlic, ginger, sesame oil and sugar.'),
(47,2,'Marinate ribs in the mixture for at least 4 hours or overnight.'),
(47,3,'Grill on high heat for 4 minutes per side until caramelised.'),
(47,4,'Garnish with sesame seeds and spring onions. Serve with rice and banchan.'),
(48,1,'Make a thin batter with flour, egg, cold water and salt.'),
(48,2,'Add sliced spring onions and seafood to the batter.'),
(48,3,'Heat oil in a pan. Pour in the batter and spread into a circle.'),
(48,4,'Cook on medium-high heat for 4 minutes until edges are crispy.'),
(48,5,'Flip carefully and cook for another 3 minutes.'),
(48,6,'Serve with a dipping sauce of soy sauce, rice vinegar and sesame oil.'),
(49,1,'Bring anchovy stock to a boil.'),
(49,2,'Dissolve doenjang paste in the stock.'),
(49,3,'Add cubed zucchini and mushrooms. Simmer for 5 minutes.'),
(49,4,'Add tofu cubes and garlic. Simmer for 5 more minutes.'),
(49,5,'Finish with a dash of sesame oil. Serve with rice.'),
(50,1,'Boil water in a small pot. Add noodles and seasoning packet.'),
(50,2,'Cook for 3 minutes.'),
(50,3,'Add any toppings: sliced spam, spring onions, an egg.'),
(50,4,'Crack egg and stir for a saucier consistency.'),
(50,5,'Serve immediately in the pot.'),
(51,1,'Marinate chicken in tikka masala, yogurt, lemon juice for 30 minutes.'),
(51,2,'Grill or pan-fry chicken until charred and cooked through.'),
(51,3,'Slice chicken into strips.'),
(51,4,'Warm tortillas. Spread with raita.'),
(51,5,'Fill with chicken, sliced onion, tomato and fresh coriander.'),
(51,6,'Fold and serve with extra raita and lemon.'),
(52,1,'Mix ground beef with blended pear, soy sauce, garlic, sesame oil and sugar.'),
(52,2,'Form into 2 patties. Pan-fry for 3 minutes per side.'),
(52,3,'Mix shredded kimchi with mayo, sesame oil and a pinch of sugar for the slaw.'),
(52,4,'Toast buns. Spread gochujang mayo on both halves.'),
(52,5,'Build burger: bun, lettuce, patty, kimchi slaw. Serve immediately.'),
(53,1,'Cook macaroni until al dente. Drain.'),
(53,2,'Make spiced bechamel: melt butter, add flour, pour in milk, whisk. Add cumin, garam masala, green chilli and diced tomato.'),
(53,3,'Stir in cheddar until melted. Season.'),
(53,4,'Mix pasta with sauce. Pour into a baking dish.'),
(53,5,'Top with extra cheese and breadcrumbs. Bake at 200C for 20 minutes until golden.'),
(54,1,'Cook sushi rice with rice vinegar, sugar and salt. Let cool.'),
(54,2,'Lay nori on a sushi mat. Spread rice leaving a 2cm border.'),
(54,3,'Layer salmon, avocado, cucumber and sriracha mayo along one edge.'),
(54,4,'Roll into a large cylinder. Wrap in cling film tightly.'),
(54,5,'Slice into rounds or leave whole as a burrito. Serve with soy sauce.'),
(55,1,'Marinate chicken in tandoori masala, yogurt, lemon juice and garlic.'),
(55,2,'Grill until cooked through with char marks.'),
(55,3,'Dice chicken. Warm a tortilla in a pan.'),
(55,4,'Add chicken and grated mozzarella to one half of tortilla.'),
(55,5,'Fold and cook in butter until golden and cheese is melted. Slice and serve.'),
(56,1,'Cook ramen noodles until al dente. Reserve cooking water.'),
(56,2,'Crisp guanciale in a dry pan. Remove.'),
(56,3,'Whisk eggs with pecorino, pepper and miso paste.'),
(56,4,'Remove pan from heat. Add hot noodles to the guanciale fat.'),
(56,5,'Pour egg mixture over noodles, tossing quickly. Add cooking water to get silky consistency.'),
(56,6,'Top with guanciale and extra cheese.'),
(57,1,'Peel and dice mangoes. Slice avocado.'),
(57,2,'Thinly slice red onion. Roughly chop coriander.'),
(57,3,'Make dressing: whisk lime juice, olive oil, chilli flakes, salt.'),
(57,4,'Combine all ingredients. Pour dressing over and toss gently.'),
(57,5,'Serve immediately as a side or light starter.'),
(58,1,'Mix grated cheddar and gruyere.'),
(58,2,'Squeeze excess liquid from kimchi and chop roughly.'),
(58,3,'Butter one side of each sourdough slice.'),
(58,4,'On unbuttered side, spread mayo. Add cheese and kimchi.'),
(58,5,'Close sandwich, butter side out.'),
(58,6,'Cook in a pan on medium heat for 3 minutes per side until golden and melted.'),
(59,1,'Marinate chicken in peri peri sauce, lemon, garlic and yogurt for at least 2 hours.'),
(59,2,'Parboil basmati rice until 70% cooked.'),
(59,3,'Cook marinated chicken in oil until nearly done.'),
(59,4,'Layer rice over chicken. Add saffron milk and fried onions.'),
(59,5,'Cover and cook on dum (low heat, sealed lid) for 25 minutes.'),
(59,6,'Gently mix before serving. Serve with raita.'),
(60,1,'Marinate chicken in tikka masala and yogurt. Grill until cooked.'),
(60,2,'Dice chicken into bite-sized pieces.'),
(60,3,'Mix coconut milk, peanut butter, lime juice and a pinch of chilli in a pan. Simmer 5 minutes.'),
(60,4,'Cook noodles. Drain.'),
(60,5,'Toss noodles in the sauce. Add chicken, spring onions and coriander.'),
(60,6,'Serve garnished with crushed peanuts and lime wedges.'),
(61,1,'Toast sourdough until golden.'),
(61,2,'Halve avocado, remove stone. Scoop out flesh into a bowl.'),
(61,3,'Mash with lemon juice, salt and chilli flakes.'),
(61,4,'Spread generously on toast.'),
(61,5,'Top with a sprinkle of sea salt and chilli flakes. Serve immediately.'),
(62,1,'Crack eggs into a bowl. Add salt and pepper. Whisk briefly.'),
(62,2,'Heat butter in a non-stick pan over medium heat.'),
(62,3,'Pour in eggs. As they set at the edges, draw them in with a spatula.'),
(62,4,'When mostly set, add grated cheddar to one half.'),
(62,5,'Fold the omelette in half. Slide onto plate. Garnish with chives.'),
(63,1,'Mince garlic finely. Mix with softened butter and chopped parsley.'),
(63,2,'Slice baguette diagonally, not cutting all the way through.'),
(63,3,'Spread garlic butter generously between each slice.'),
(63,4,'Wrap in foil. Bake at 200C for 10 minutes.'),
(63,5,'Open foil for last 3 minutes to crisp the top. Serve immediately.'),
(64,1,'Spread tortilla chips on a baking tray.'),
(64,2,'Grate cheddar generously over chips.'),
(64,3,'Scatter sliced jalapenos over cheese.'),
(64,4,'Bake at 200C for 8 minutes until cheese is melted and bubbly.'),
(64,5,'Top with salsa, sour cream and guacamole. Serve immediately.'),
(65,1,'Bring a pan of water to a rolling boil.'),
(65,2,'Gently lower eggs in with a spoon.'),
(65,3,'Cook for exactly 6 minutes for runny yolk.'),
(65,4,'Transfer to ice water immediately to stop cooking.'),
(65,5,'Peel carefully. Serve with buttered toast cut into soldiers.'),
(66,1,'Peel and slice bananas.'),
(66,2,'Add bananas, yogurt, oats, honey and milk to a blender.'),
(66,3,'Blend until completely smooth.'),
(66,4,'Pour into a glass. Drink immediately or refrigerate for up to one day.'),
(67,1,'Warm a pan over medium heat.'),
(67,2,'Place a tortilla in the pan. Add cheese and vegetables to one half.'),
(67,3,'Fold the tortilla in half.'),
(67,4,'Cook for 2 minutes until golden. Flip and cook 2 more minutes.'),
(67,5,'Slice into wedges. Serve with sour cream and salsa.'),
(68,1,'Toast bread to your liking.'),
(68,2,'Spread peanut butter generously.'),
(68,3,'Slice banana and layer on top.'),
(68,4,'Drizzle with honey. Serve immediately.'),
(69,1,'Mix flour with salt and water to form a soft dough. Rest 10 minutes.'),
(69,2,'Divide into portions. Roll each into a thin round.'),
(69,3,'Fold into thirds and roll out again for layers. Repeat once.'),
(69,4,'Cook on a hot tawa with butter, pressing edges down.'),
(69,5,'Serve hot with a cup of cardamom chai.'),
(70,1,'Make a stiff dough with flour, salt and oil.'),
(70,2,'Boil potatoes. Mash with peas, cumin, garam masala, green chilli and coriander.'),
(70,3,'Roll dough thin. Cut into circles and fill with potato mixture.'),
(70,4,'Seal edges into a triangle shape. Deep fry until golden.'),
(70,5,'Serve with mint chutney and tamarind sauce.'),
(71,1,'Remove steak from fridge 30 minutes before cooking. Pat dry. Season well.'),
(71,2,'Heat a cast iron pan until smoking. Add oil.'),
(71,3,'Sear steak 3 minutes per side without moving.'),
(71,4,'Add butter, garlic, rosemary and thyme. Baste steak with foaming butter for 2 minutes.'),
(71,5,'Rest steak for 5 minutes before slicing. Serve with chips or salad.'),
(72,1,'Pat salmon dry. Season with salt, pepper and lemon zest.'),
(72,2,'Heat oven to 200C. Place salmon on a lined baking tray.'),
(72,3,'Drizzle with olive oil and scatter dill on top.'),
(72,4,'Bake for 12-15 minutes until flesh flakes easily.'),
(72,5,'Serve with lemon wedges and your choice of salad.'),
(73,1,'Grill or pan-fry seasoned chicken breast. Slice.'),
(73,2,'Wash and tear romaine lettuce. Place in a large bowl.'),
(73,3,'Add croutons, shaved parmesan and chicken.'),
(73,4,'Drizzle with Caesar dressing. Toss gently.'),
(73,5,'Serve immediately with extra parmesan.'),
(74,1,'Mix olive oil, garlic, rosemary, salt and pepper.'),
(74,2,'Rub marinade all over lamb chops. Marinate for 1 hour.'),
(74,3,'Heat grill or griddle pan until very hot.'),
(74,4,'Grill chops for 3 minutes per side for medium-rare.'),
(74,5,'Rest for 5 minutes. Serve with mint sauce and roasted potatoes.'),
(75,1,'Mix BBQ sauce with garlic powder, paprika and a pinch of cayenne.'),
(75,2,'Score chicken pieces. Rub with oil and season.'),
(75,3,'Grill on medium heat for 15 minutes, turning occasionally.'),
(75,4,'Baste with BBQ sauce in the last 10 minutes of cooking.'),
(75,5,'Serve with coleslaw and corn on the cob.'),
(76,1,'Make batter: whisk flour, baking powder, beer and salt until smooth. Rest 10 min.'),
(76,2,'Cut potatoes into thick chips. Parboil for 5 minutes. Drain and cool.'),
(76,3,'Fry chips at 160C for 8 minutes. Drain.'),
(76,4,'Dip fish in batter. Fry at 180C for 5 minutes until golden.'),
(76,5,'Fry chips again at 190C for 3 minutes until crispy. Serve together with vinegar.'),
(77,1,'Brown ground beef with taco seasoning and onion. Drain fat.'),
(77,2,'Warm taco shells in the oven for 3 minutes.'),
(77,3,'Fill shells with beef, shredded cheese, lettuce and tomato.'),
(77,4,'Top with sour cream and salsa. Serve immediately.'),
(78,1,'Marinate chicken in yogurt, shawarma spice, garlic and lemon juice for at least 4 hours.'),
(78,2,'Grill on high heat for 15 minutes until cooked through and slightly charred.'),
(78,3,'Slice chicken thinly.'),
(78,4,'Warm flatbread. Spread with garlic sauce.'),
(78,5,'Layer chicken, tomato and onion. Roll tightly and serve.'),
(79,1,'Fry onions until deep golden. Add ginger-garlic paste.'),
(79,2,'Add lamb and brown on high heat.'),
(79,3,'Add whole spices, yogurt and almond paste. Mix well.'),
(79,4,'Add 300ml water. Cover and simmer on low heat for 45 minutes.'),
(79,5,'Stir in cream and saffron. Simmer for 15 more minutes.'),
(79,6,'Garnish with fried onions and serve with naan.'),
(80,1,'Fry green curry paste in a little oil until fragrant.'),
(80,2,'Add coconut milk. Bring to a simmer.'),
(80,3,'Add chicken pieces. Cook for 15 minutes.'),
(80,4,'Season with fish sauce and sugar.'),
(80,5,'Add Thai basil and lime juice. Serve over jasmine rice.'),
(81,1,'Halve tomatoes. Toss with olive oil, salt, a pinch of sugar.'),
(81,2,'Roast at 200C for 25 minutes until soft.'),
(81,3,'Saute onion and garlic in olive oil until soft.'),
(81,4,'Add roasted tomatoes and stock. Simmer 10 minutes.'),
(81,5,'Blend until smooth. Stir in cream. Season and serve with garlic bread.'),
(82,1,'Saute onion, garlic and cumin in olive oil until soft.'),
(82,2,'Add tomatoes and cook for 3 minutes.'),
(82,3,'Add lentils and stock. Bring to a boil. Simmer 20 minutes.'),
(82,4,'Use a hand blender to blend partially for a creamy texture.'),
(82,5,'Season and squeeze in lemon juice. Serve with crusty bread.'),
(83,1,'Dice cucumber, quarter tomatoes, slice red onion thinly.'),
(83,2,'Combine with olives and crumbled feta in a bowl.'),
(83,3,'Whisk olive oil, lemon juice, oregano and salt.'),
(83,4,'Pour dressing over salad. Toss gently. Serve immediately.'),
(84,1,'Simmer chicken pieces in stock with onion, celery, carrot and bay leaf.'),
(84,2,'Remove chicken after 20 minutes. Shred meat. Discard bones.'),
(84,3,'Add noodles to the broth. Cook until tender.'),
(84,4,'Return shredded chicken to the pot. Season.'),
(84,5,'Serve garnished with fresh parsley.'),
(85,1,'Blanch and rinse beef bones. Simmer for 3 hours with star anise, cinnamon and ginger.'),
(85,2,'Strain broth. Season with fish sauce, salt and sugar.'),
(85,3,'Cook rice noodles separately. Drain.'),
(85,4,'Thinly slice raw beef. Place in bowls with noodles.'),
(85,5,'Pour hot broth over to cook the beef.'),
(85,6,'Serve with bean sprouts, basil, lime and hoisin sauce.'),
(86,1,'Make dressing: blend garlic, anchovy, lemon, egg yolk, worcestershire sauce.'),
(86,2,'Slowly whisk in olive oil until emulsified. Season.'),
(86,3,'Tear romaine into a large bowl.'),
(86,4,'Add croutons and half the dressing. Toss well.'),
(86,5,'Plate and top with extra dressing and shaved parmesan.'),
(87,1,'Heat dashi stock to just below boiling. Do not boil.'),
(87,2,'Dissolve miso paste in a ladle of the warm stock. Stir back in.'),
(87,3,'Add cubed silken tofu gently.'),
(87,4,'Add rehydrated wakame.'),
(87,5,'Garnish with thinly sliced spring onions. Serve immediately.'),
(88,1,'Blend tomatoes, cucumber, red pepper, onion, garlic with olive oil and vinegar.'),
(88,2,'Pass through a sieve for a smooth texture.'),
(88,3,'Season with salt and chill for at least 2 hours.'),
(88,4,'Serve cold in bowls with a drizzle of olive oil and diced vegetables on top.'),
(89,1,'Melt chocolate and butter together. Cool slightly.'),
(89,2,'Whisk eggs and sugar until thick and pale.'),
(89,3,'Fold in chocolate mixture.'),
(89,4,'Sift in flour and cocoa. Fold gently.'),
(89,5,'Butter ramekins. Pour in batter to three-quarters full.'),
(89,6,'Bake at 200C for exactly 12 minutes. The centre should wobble slightly.'),
(89,7,'Turn out immediately onto plates and serve with ice cream.'),
(90,1,'Wash rice and soak for 10 minutes.'),
(90,2,'Bring milk to a gentle boil. Add rice.'),
(90,3,'Simmer on low heat for 35 minutes, stirring frequently.'),
(90,4,'Add sugar, cardamom and rose water. Stir well.'),
(90,5,'Pour into bowls. Garnish with chopped almonds and pistachios.'),
(90,6,'Serve warm or chilled.'),
(91,1,'Mix milk powder, flour and baking soda. Add enough milk to form a soft dough.'),
(91,2,'Roll into small smooth balls.'),
(91,3,'Deep fry in medium-low oil for 10 minutes, turning gently, until deep brown.'),
(91,4,'Make syrup: boil sugar, water, cardamom and rose water until slightly sticky.'),
(91,5,'Soak fried balls in hot syrup for 30 minutes. They will absorb the syrup and puff up.'),
(91,6,'Serve warm garnished with pistachios.'),
(92,1,'Whip heavy cream to soft peaks.'),
(92,2,'Fold in condensed milk and mango puree.'),
(92,3,'Add cardamom powder. Mix well.'),
(92,4,'Pour into kulfi moulds or paper cups. Insert sticks.'),
(92,5,'Freeze for at least 6 hours or overnight.'),
(92,6,'To serve, run warm water over moulds briefly to unmould.'),
(93,1,'Whisk flour, baking powder, sugar and salt.'),
(93,2,'Mix eggs, milk, melted butter and vanilla.'),
(93,3,'Combine wet and dry ingredients until just mixed. Do not overmix. Lumps are fine.'),
(93,4,'Heat a non-stick pan. Add a little butter.'),
(93,5,'Pour a ladleful of batter. Cook until bubbles form on surface.'),
(93,6,'Flip and cook 1 more minute. Serve stacked with maple syrup and butter.'),
(94,1,'Mash very ripe bananas with a fork.'),
(94,2,'Mix in melted butter and sugar.'),
(94,3,'Add beaten eggs and vanilla. Mix.'),
(94,4,'Fold in flour, baking soda, cinnamon and walnuts.'),
(94,5,'Pour into a greased loaf tin.'),
(94,6,'Bake at 180C for 55 minutes. A skewer should come out clean.'),
(94,7,'Cool before slicing.'),
(95,1,'Make base: crush biscuits, mix with melted butter. Press into a lined tin. Chill.'),
(95,2,'Beat cream cheese until smooth. Add sugar, vanilla and lemon zest.'),
(95,3,'Add eggs one at a time, mixing gently.'),
(95,4,'Fold in sour cream.'),
(95,5,'Pour over biscuit base. Bake in a water bath at 160C for 60 minutes.'),
(95,6,'Turn oven off and leave inside for 1 hour to prevent cracks.'),
(95,7,'Refrigerate overnight before serving.'),
(96,1,'Mix soy sauce, mirin, sake and sugar. Simmer until slightly reduced to make tare.'),
(96,2,'Score chicken thighs. Coat in tare sauce.'),
(96,3,'Grill skin-side down on medium-high heat for 6 minutes.'),
(96,4,'Flip and brush with more tare. Grill for another 6 minutes.'),
(96,5,'Brush again. Rest for 3 minutes. Slice and serve over rice.'),
(97,1,'Mix pork, finely chopped cabbage, garlic, ginger, soy sauce and sesame oil.'),
(97,2,'Place a teaspoon of filling on each wrapper. Pleat and seal.'),
(97,3,'Heat oil in a pan. Place dumplings flat-side down and fry until golden.'),
(97,4,'Add 60ml water and cover immediately. Steam for 5 minutes.'),
(97,5,'Remove lid and cook off remaining water.'),
(97,6,'Serve with dipping sauce of soy, vinegar and sesame oil.'),
(98,1,'Cook sushi rice. Season with rice vinegar, sugar and salt while warm. Cool.'),
(98,2,'Drain and flake tuna. Mix with mayo.'),
(98,3,'Wet hands. Take a handful of rice and form into a ball.'),
(98,4,'Make a well and fill with tuna mixture.'),
(98,5,'Mould into a triangle shape. Wrap with a strip of nori.'),
(98,6,'Serve with soy sauce for dipping.'),
(99,1,'Cut chicken into bite-sized pieces. Thread onto soaked skewers.'),
(99,2,'Mix soy sauce, mirin, sake, sugar and garlic for tare sauce.'),
(99,3,'Simmer tare until slightly thickened.'),
(99,4,'Grill skewers on high heat for 8 minutes, turning and basting with tare.'),
(99,5,'Serve sprinkled with spring onions and a side of rice.'),
(100,1,'Simmer pork bones and aromatics for at least 4 hours for a milky broth. Strain.'),
(100,2,'Season broth with soy sauce, salt and a little sesame oil.'),
(100,3,'Slice chashu pork belly. Warm soft-boiled marinated eggs.'),
(100,4,'Cook ramen noodles until al dente. Drain.'),
(100,5,'Place noodles in bowls. Pour over very hot broth.'),
(100,6,'Arrange chashu, halved egg, nori, bamboo shoots, corn and spring onions on top.');